apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pythonapp.fullname" . }}-cm
  labels:
    {{- include "pythonapp.labels" . | nindent 4 }}
data:
  dbhost: pythondb-service
  dbport: {{ .Values.mongodbdata.dbport | quote }}
  dbuser: {{ .Values.mongodbdata.dbuser | quote }}
